@startuml 1

class 基金 {
    + 购买()
    + 赎回()
}

class 股票1{
    + 买()
    + 卖()
}

class 股票2{
    + 买()
    + 卖()
}

class 国债1{
    + 买()
    + 卖()
}

class 房地产1{
    + 买()
    + 卖()
}

客户 --> 基金

基金 o--> 股票1
基金 o--> 股票2
基金 o--> 国债1
基金 o--> 房地产1


@enduml