@startuml 1

class 股票1{
    + 买()
    + 卖()
}

class 股票2{
    + 买()
    + 卖()
}

class 国债1{
    + 买()
    + 卖()
}

class 房地产1{
    + 买()
    + 卖()
}

客户 --> 股票1
客户 --> 股票2
客户 --> 国债1
客户 --> 房地产1


@enduml