@startuml "7.3"

interface 送礼物 {
    + 送洋娃娃()
    + 送鲜花()
    + 送巧克力()
}

class 被追求者 {
    + 姓名
}

class 代理 implements 送礼物 {
    + 送洋娃娃()
    + 送鲜花()
    + 送巧克力()
}

class 追求者 implements 送礼物 {
    + 送洋娃娃()
    + 送鲜花()
    + 送巧克力()
}

追求者 <-- 代理
被追求者 <.. 代理

@enduml